version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - typesense
      - vad
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - VAD_SERVICE_URL=http://vad:8081/v1/vad
      - HOSTED_VAD_API_URL=http://vad:8081/v1/vad
      - HOSTED_PUSHER_API_URL=http://pusher:80
      - GOOGLE_APPLICATION_CREDENTIALS=/app/application_default_credentials.json
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/app/application_default_credentials.json:ro

  vad:
    platform: linux/amd64  # emulate amd64
    env_file:
      - .env
    build:
      context: .
      dockerfile: modal/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/application_default_credentials.json
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/app/application_default_credentials.json:ro


  pusher:
    build:
      context: .
      dockerfile: pusher/Dockerfile  # Adjust if you use a specific Dockerfile name
    env_file:
      - .env
    ports:
      - "8090:80"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/application_default_credentials.json
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/app/application_default_credentials.json:ro

      

  redis:
    image: redis:6.2-alpine
    container_name: redis_container
    command: redis-server --requirepass ${REDIS_DB_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  typesense:
    image: typesense/typesense:0.25.1
    container_name: typesense_container
    env_file:
      - .env
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense_data:/data
    ports:
      - "8108:8108"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
  typesense_data:
